<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MAIN" Id="{7a206d30-1839-491e-a1bd-10b80568af76}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
        test AT%MD0 : DINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[test := test + 1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>